// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALf0PsEWQQlO-WJiMzReKrxaW0eLn-m6o',
    appId: '1:698007809376:web:537b631e862e2cb3310205',
    messagingSenderId: '698007809376',
    projectId: 'simasjid-fe5e5',
    authDomain: 'simasjid-fe5e5.firebaseapp.com',
    storageBucket: 'simasjid-fe5e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtW5t2uh6OqjUhCj1PNh9nHH_FPNQ1LgY',
    appId: '1:698007809376:android:6f2bd558b8ca2dcf310205',
    messagingSenderId: '698007809376',
    projectId: 'simasjid-fe5e5',
    storageBucket: 'simasjid-fe5e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKPyu8CJIj4oRta1oDldqU2pU0pMMUSf0',
    appId: '1:698007809376:ios:81be3b71896bfc0e310205',
    messagingSenderId: '698007809376',
    projectId: 'simasjid-fe5e5',
    storageBucket: 'simasjid-fe5e5.appspot.com',
    iosClientId: '698007809376-190kdqp7l45olfd5pjlq1hm8ikr25ks7.apps.googleusercontent.com',
    iosBundleId: 'com.example.simasjid',
  );
}
